# Generated by Django 2.0.4 on 2020-01-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0008_gate_name'),
        ('meta', '0008_merge_20190812_0048'),
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100, verbose_name='车牌')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.Gate')),
                ('parkinglot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.User')),
            ],
            options={
                'verbose_name': '用户提交异常',
            },
        ),
    ]
